# Generated by Django 4.2.7 on 2025-10-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='generatedimage',
            name='room_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generatedimage',
            name='style',
            field=models.CharField(max_length=50),
        ),
    ]
